// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { ReduxProvider } from "@/store/provider";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Hoops Net",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   return (
      <html
         lang='en'
         className='h-full bg-white text-black dark:bg-zinc-900 dark:text-white'
      >
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
         >
            <Toaster position='bottom-center' />
            <ReduxProvider>{children}</ReduxProvider>
         </body>
      </html>
   );
}
